version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: foreman run bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - '.env'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
