version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - "./db/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    expose:
      - "5432"
  redis:
    image: redis:3.0.4
    ports:
      - "6379:6379"
    expose:
      - "6379"
