# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ea488ac5942f981f0d9388bf3a73eaa50a7b3ac9514709fcf869ae1a961f539d21e710101ef168708df39d8aea658b65f695ace9c242ae6e2732505a53dee74e

test:
  secret_key_base: ef797f09df2f74f7af4b13f3f78a0c2b79535930e1fd75b4e593d51fea4176d481aebb3cd24ec821ed55125b91b9da8da02ee6818ee380541f9196566ffb8fde

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
